
language: objective-c

before_install:
    - gem install cocoapods --quiet
    - pod --version
    - pod setup
    - pod repo update --silent
    - export LANG=en_US.UTF-8
    - env
    - locale

script:
    - pod lib lint
    - cd Demo
    - pod repo update --silent
    - pod update
    - xctool -workspace NBULogDemo.xcworkspace -scheme 'NBULogDemo' -configuration Release -sdk iphonesimulator -arch i386 build
